### ISSUE TITLE
[ERROR] Registry key: ... doesn't exist

### ISSUE THREAD

**Issue by cryptix** [ssbc/scuttle-shell#15]
Just got this trying to install on a fresh installed system.

```
> scuttle-shell@0.1.0 install C:\Users\ssb\Desktop\patchbay\node_modules\scuttle-shell
> node scripts/install.js

{"HKCU\\Software\\Mozilla\\NativeMessagingHosts\\scuttleshell":
[ERROR] Registry key: HKCU\Software\Mozilla\NativeMessagingHosts\scuttleshell doesn't exist

Try: npm run setup-win%
```

Not really versed in windows registration stuff but a first thought: do the parent keys have to exist?

**Comment by cryptix** [comment]
site-note on electron packaging: https://github.com/ironSource/node-regedit#a-note-about-electron

**Comment by cryptix** [comment]
https://ci.appveyor.com/project/cryptix/scuttle-shell/builds/19661711#L64

**Comment by mixmix** [comment]
Can confirm I saw this as well

**Comment by cryptix** [comment]
All this registry stuff is only needed for the host_app.js, which is used by WebExtensions to create sbot instances.

I’m torn on having it in this module as well. Having it’s own repo would be cleaner and allow us to focus on the needed features and tests. A dedicated module would then import the shell and use it, like any other app would.

**Comment by mixmix** [comment]
Yah i feel the same way. Seperating this logic in some way feels right.
It could be done now (or isolated in a function which can option alt be
called)  or done later if its not causing trouble (seems to be ok atm)

**Comment by soapdog** [comment]
I am closing this issue because the registry and native messaging code is moving out of this module.
