### ISSUE TITLE
move to ssbc?

### ISSUE THREAD

**Issue by mixmix** [ssbc/scuttle-shell#2]
hey @soapdog would you be happy moving this into github.com/ssbc ?
mainly I'm interested in easy ways for people to find it, and for core contributors to be able to push branches up to help contribute

if you're not into it, thanks fine

**Comment by mixmix** [comment]
Added a git-ssb repo in the meantime : `ssb://%AVhVlwiF+1XgnJMWJYxGbUP9mG87kzoAuwfmho/stYc=.sha256`

**Comment by mixmix** [comment]
@soapdog this is already working. Without changing anything in Patchbay, when you start it, the sbot process crashes because it the port is already in use by scuttle-shell.

This model will work exactly the same for Patchwork and Ticktack, we just need to extract the plugins those apps are running but haven't published (or ask the authors to publish them, or join this conversation cc @mmckegg )

My ideal would be to rip out the custom sbot stuff in patchbay and drop something which can start a standalone scuttle-shell if it's not already running (and leave it running).

**Comment by soapdog** [comment]
@mixmix if you `require('scuttle-shell')`, you can (after implementing some detection of running _sbot_), you can use `scuttleshell.start()` to launch it. I do need to make a way for it not to start a second shell...

**Comment by soapdog** [comment]
@mixmix  Transferring to SSBC now.

**Comment by soapdog** [comment]
Move completed!
