### ISSUE TITLE
Global install fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by galerykaeser** [ssbc/scuttle-shell#27]
I ran `npm install -g scuttle-shell` and got the following warnings:

    npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
    npm WARN lifecycle forked-systray@3.0.11~preinstall: cannot run in wd %s %s (wd=%s) forked-systray@3.0.11 node ./scripts/fetch-prebuilt-helper.js /usr/local/lib/node_modules/.staging/forked-systray-485944e9
    prebuild-install WARN install EACCES: permission denied, access '/home/myname/.npm'
    npm WARN optional Skipping failed optional dependency /scuttle-shell/chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
    npm WARN optional Skipping failed optional dependency /scuttle-shell/ssb-server/chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9

When running `scuttleshell`, I get the following error:

    SyntaxError: Unexpected token T in JSON at position 0
        at parse (<anonymous>)
        at /usr/local/lib/node_modules/scuttle-shell/node_modules/pull-stream/throughs/map.js:13:23
        at /usr/local/lib/node_modules/scuttle-shell/node_modules/pull-stream/throughs/filter.js:17:11
        at pull (/usr/local/lib/node_modules/scuttle-shell/node_modules/pull-through/index.js:46:22)
        at next (/usr/local/lib/node_modules/scuttle-shell/node_modules/looper/index.js:7:11)
        at /usr/local/lib/node_modules/scuttle-shell/node_modules/looper/index.js:9:18
        at /usr/local/lib/node_modules/scuttle-shell/node_modules/pull-through/index.js:62:13
        at /usr/local/lib/node_modules/scuttle-shell/node_modules/pull-stream/throughs/through.js:19:9
        at drain (/usr/local/lib/node_modules/scuttle-shell/node_modules/stream-to-pull-stream/index.js:126:18)
        at Socket.<anonymous> (/usr/local/lib/node_modules/scuttle-shell/node_modules/stream-to-pull-stream/index.js:135:5)

After some searching, I found out that it is trying to parse `This file should have been replaced by the preinstall script of forked-systray` as JSON. This can be found in [/blob/master/systrayhelper](https://github.com/ssbc/forked-systray/blob/master/systrayhelper) in ssbc/forked-systray, which seems to imply that the installation of systray was unsuccessful. Further evidence is the second warning I got when installing. 

---

To provide some context: Before trying to install scuttleshell I had installed Patchwork, but it was not running during the installation or setup process.

Some information about my system:

    Linux myPC 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dominictarr** [comment]
I tried this and it worked... (scuttle-shell@1.0.1) maybe it's just a race condition or fixed in a newer version, can you try again?
