### ISSUE TITLE
Should this repository be archived?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/scuttle-shell#30]
I was trying to help move those PRs forward but I realized that I'm not sure who is maintaining it.

cc: @cryptix @soapdog

**Comment by soapdog** [comment]
I'm working on it @christianbundy 

I'm taking over maintenance for this. I'm still trying to get a way to ship standalone versions of this app and thats why I've been working on package managers today. It might be viable to distribute as source.

The Patchfox Open Collective will work on this as part of its stuff.

**Comment by christianbundy** [comment]
Sounds great, thanks!
