### ISSUE TITLE
Support Custom Plugins

### ISSUE THREAD

**Issue by Happy0** [ssbc/scuttle-shell#7]
# Objective

At the moment, scuttle-shell automatically injects a bunch of commonly used (across patchwork and batchbay) scuttlebot plugins.

However, there isn't any way for an application which consumes scuttle-shell to inject custom plugins that aren't available (as far as I know - feel free to close if I'm mistaken.)

# Brief aside for thanks =p

Thanks, @soapdog , scuttle-shell is awesome.

# Why (anyway, back on topic.)

Applications which consume scuttle-shell may use custom scuttlebot plugins which aren't used by the main clients.

# Desired Outcome

- A consuming application can inject custom scuttlebot plugins into the scuttlebot instance that is started.
- There is some documentation in the README.md file that gives an example of how to do this.
- Initiating the ssb-chess-db plugin (used to support the chess feature in patchbay) could **perhaps** be moved out of server.js and into patchbay when it initialises scuttle-shell instead. Other applications that use ssb-chess in the future could do the same.

**Comment by soapdog** [comment]
Working on it

**Comment by soapdog** [comment]
@Happy0 I've added support for custom plugins but I haven't added any form of checking for conflicts or safety.

It is on the https://github.com/ssbc/scuttle-shell/tree/enhancement-custom-plugins

It supports custom plugins from two different sources, one is adding a `plugins` array to `scuttleshell.json` another is passing a _custom configuration object_ to the `scuttleshell.start()` call like:

```
scuttleshell.start({ 
  plugins: ["./examples/service-discovery"] 
})
```

There is a new sample at `examples/launch_sbot_custom_plugin.js`
cc @mixmix @cryptix

**Comment by cryptix** [comment]
As of  v0.1 we have this and the `--extra-plugin` command line flag to do this. 

@Happy0 please re-open if this doesn't suite you.

I'm still hassitant about the _install on demand during init_... I'd rather apps install their deps and then pass the path were it can be loaded.
